# Generated by Django 2.2.12 on 2021-08-30 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20210827_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressao',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastros.Classe', verbose_name='classe pretendida'),
            preserve_default=False,
        ),
    ]
